catalyst_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
    path('accounts/', include('allauth.urls')),

]

company/urls.py
from django.urls import path
from company.views import rest_apis_view, user_views, views

app_name = 'Company'

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view_new, name="logout"),
    path('query_page/', views.query_builder_view, name="query_page"),
    path('users/', user_views.user_list_view, name="user_list"),
    path('users/delete/<int:id>', user_views.user_delete_view, name="user_delete"),
    path('users/create', user_views.user_create, name="user_create"),
    path('api/query', rest_apis_view.CompanyQueryView.as_view(), name="api_query")

]

company/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

#
# class Company(models.Model):
#     id = models.BigIntegerField(primary_key=True)
#     name = models.TextField(blank=True, null=True)
#     domain = models.TextField(blank=True, null=True)
#     year_founded = models.FloatField(db_column='year founded', blank=True, null=True)  # Field renamed to remove unsuitable characters.
#     industry = models.TextField(blank=True, null=True)
#     size_range = models.TextField(db_column='size range', blank=True, null=True)  # Field renamed to remove unsuitable characters.
#     locality = models.TextField(blank=True, null=True)
#     country = models.TextField(blank=True, null=True)
#     linkedin_url = models.TextField(db_column='linkedin url', blank=True, null=True)  # Field renamed to remove unsuitable characters.
#     current_employee_estimate = models.BigIntegerField(db_column='current employee estimate', blank=True, null=True)  # Field renamed to remove unsuitable characters.
#     total_employee_estimate = models.BigIntegerField(db_column='total employee estimate', blank=True, null=True)  # Field renamed to remove unsuitable characters.
#
#     class Meta:
#         db_table = 'company'

class Company(models.Model):
    id = models.BigIntegerField(primary_key=True)
    name = models.TextField(blank=True, null=True)
    domain = models.TextField(blank=True, null=True)
    year_founded = models.FloatField(db_column='year founded', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    industry = models.TextField(blank=True, null=True)
    size_range = models.TextField(db_column='size range', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    locality = models.TextField(blank=True, null=True)
    country = models.TextField(blank=True, null=True)
    linkedin_url = models.TextField(db_column='linkedin url', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    current_employee_estimate = models.BigIntegerField(db_column='current employee estimate', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    total_employee_estimate = models.BigIntegerField(db_column='total employee estimate', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    city = models.TextField(blank=True, null=True)
    state = models.TextField(blank=True, null=True)
    country1 = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'company4'

company/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
class UserCreateForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2', 'is_staff')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'email': forms.EmailInput(attrs={'class': "form-control", 'placeholder': 'email@email.com'}),
        }

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise ValidationError("Email already exists")
        return email

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name'].lower()

        if not first_name.isalpha():
            raise ValidationError("Only Alphabets!")
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name'].lower()

        if not last_name.isalpha():
            raise ValidationError("Only Alphabets!")
        return last_name

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 8:
            raise ValidationError("Password is short")
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")
        return password2

company/views/rest_apis_view.py
from rest_framework.views import APIView
from company.models import Company
from rest_framework import serializers
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated


class CompanyQueryView(APIView):
    def get(self, request):
        data = request.GET
        data2 = {}
        for i in data:
            if i == 'name':
                data2['name__contains'] = data[i]
            elif i == 'employee_from':
                data2['current_employee_estimate__gte'] = int(data[i])
            elif i == 'employee_to':
                data2['current_employee_estimate__lte'] = int(data[i])
            else:
                data2[i] = data[i]

        print(data, data2)

        output_data = Company.objects.filter(**data2).count()
        return Response({"status": "success", "data": output_data}, status=status.HTTP_200_OK)


class CompanyIndustrySerializer(serializers.ModelSerializer):
    industry = serializers.CharField(max_length=255)

    class Meta:
        model = Company
        fields = ('industry',)

company/views/user_views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as default_logout, authenticate, login
from django.contrib import messages
from django.contrib.auth import get_user_model
from company.forms import UserCreateForm
from django.contrib.auth.decorators import login_required


@login_required
def user_list_view(request):
    model_user = get_user_model()
    user_list = model_user.objects.all()
    return render(request, 'company/user_list_pages/user_list.html', context={'users': user_list})


@login_required
def user_delete_view(request, id):
    User = get_user_model()
    try:
        u = User.objects.get(id=id)
        u.delete()
        messages.success(request, "The user is deleted")
        return redirect("Company:user_list")
    except User.DoesNotExist:
        messages.error(request, "User doesnot exist")
        return redirect("Company:user_list")


@login_required
def user_create(request):
    if request.method == 'POST':
        form_user_create = UserCreateForm(request.POST)
        if form_user_create.is_valid():
            form_user_create.save()
            return redirect('Company:user_list')
    else:
        form_user_create = UserCreateForm()
    return render(request, 'company/user_list_pages/user_create.html', {"form1": form_user_create})

company/views/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from company.models import Company
from django.contrib.auth.decorators import login_required


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('Company:query_page')
        else:
            messages.error(request, "Username password did not match!")
            return render(request, 'company/auth_pages/login.html')
    else:
        return render(request, 'company/auth_pages/login.html')


@login_required
def logout_view_new(request):
    logout(request)
    return redirect('Company:login')


@login_required
def query_builder_view(request):
    industry = Company.objects.order_by('industry').values_list('industry', flat=True).distinct()
    city = Company.objects.order_by('city').values_list('city', flat=True).distinct()
    state = Company.objects.order_by('state').values_list('state', flat=True).distinct()
    country = Company.objects.order_by('country').values_list('country', flat=True).distinct()
    year_founded = list(Company.objects.order_by('year_founded').values_list('year_founded', flat=True).distinct())
    year_founded.remove(None)
    year_founded = list(map(int, year_founded))
    data = {
        'industry': industry,
        'year_founded': year_founded,
        'state': state,
        'city': city,
        'country': country
    }
    return render(request, 'company/query_page.html', context=data)

templates/company/user_list_pages/user_create.html
{% extends   'company/common_pages/main_contain.html' %}

{% block title %}
<title>Users | Create</title>
{% endblock %}
{% block navbar %}
<li class="nav-item ">
    <a class="nav-link" href="{% url  'Company:query_page' %}">Query Builder <span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
    <a class="nav-link" href="{% url  'Company:user_list' %}">Users</a>
</li>
{% endblock %}
{% block contentblock %}
<div style="margin:1%">
    <div>
        <h1 >Users</h1>
    </div>
    <style>
        .error {color:red;}
    </style>
    <div class="form">
    <form role="form" method="POST">
        <div class="box-body">
            {% csrf_token  %}

            <div class="form-group">
                <label >UserName<span class="error">{{form1.username.errors |striptags}}</span></label>
                {{form1.username}}
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">First Name<span class="error">{{form1.first_name.errors |striptags}}</span></label>
                {{form1.first_name}}
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Last Name<span class="error">{{form1.last_name.errors |striptags}}</span></label>
                {{form1.last_name}}
            </div>
            <div class="form-group">
                <label>Password <span class="error">{{form1.password1.errors |striptags}}</span></label>
                {{form1.password1}}
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Confirm Password<span class="error">{{form1.password2.errors |striptags}}</span></label>
                {{form1.password2}}
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Email address<span class="error">{{form1.email.errors |striptags}}</span></label>
                {{form1.email}}
            </div>

                <label>Staff Member</label>
                {{form1.is_staff}}


        </div>
        <!-- /.box-body -->
        <div class="box-footer">

            <button type="submit" class="btn btn-primary">Submit</button> &nbsp;
            <a href="{% url  'Company:user_list' %}">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </a>
        </div>
    </form>
    </div>
</div>
{% endblock %}
</body>
</html>

templates/company/user_list_pages/user_list.html
{% extends   'company/common_pages/main_contain.html' %}

{% block title %}
<title>Users</title>
{% endblock %}
{% block navbar %}
<li class="nav-item ">
    <a class="nav-link" href="{% url  'Company:query_page' %}">Query Builder <span class="sr-only">(current)</span></a>
</li>
<li class="nav-item active">
    <a class="nav-link" href="{% url  'Company:user_list' %}">Users</a>
</li>
{% endblock %}
{% block contentblock %}
<div style="margin:1%">
    <div style="display:block">
        <h1 style="float:left">Users</h1>
        <a href="{% url  'Company:user_create' %}">
            <button class="btn btn-primary" style="float:right">Create User</button>
        </a>
    </div>
    <table class="table">
        <tr>
            <th>
                Username
            </th>
            <th>
                Email
            </th>
            <th>
                Active
            </th>
            <th></th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{user.username}}</td>
            <td>{{user.email}}</td>
            {% if user.active %}
            <td>Active</td>
            {% else %}
            <td>Inactive</td>
            {% endif %}
            <td>
                <a href="{% url  'Company:user_delete' user.id %}">
                    <button onclick="return confirm('confirm Delete?')">
                        <i class='fa fa-close'></i>
                    </button>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}
</body>
</html>